// Jouw vaste, centrale woordenlijst
const fixedWerkwoordenlijst = [
    { nl: "openen", es: "abrir" },
    { nl: "vastmaken", es: "abrochar" },
    { nl: "Stoppen", es: "acabar" },
    { nl: "aanvaarden | accepteren", es: "aceptar" },
    { nl: "naar bed gaan | gaan liggen om te rusten", es: "acostarse" },
    { nl: "afvallen | vermageren", es: "adelgazar" },
    { nl: "zich scheren", es: "afeitarse" },
    { nl: "verdrinken", es: "ahogar" },
    { nl: "africhten", es: "amaestrar" },
    { nl: "toevoegen", es: "añadir | agregar" },
    { nl: "lopen |wandelen", es: "andar" },
    { nl: "parkeren", es: "aparcar" },
    { nl: "leren", es: "aprender" },
    { nl: "knijpen | indrukken | spannen (kleding)", es: "apretar" },
    { nl: "zich opfrissen", es: "asearse" },
    { nl: "vertonen", es: "asomar" },
    { nl: "verbazen | versteld doen staan", es: "asombrar" },
    { nl: "afschrikken | verschieten", es: "asustar" },
    { nl: "vangen", es: "atrapar" },
    { nl: "durven", es: "atrever" },
    { nl: "omrijden | aanrijden", es: "atropellar" },
    { nl: "helpen", es: "ayudar" },
    { nl: "dansen", es: "bailar" },
    { nl: "vegen", es: "barrer" },
    { nl: "zich baden", es: "bañarse" },
    { nl: "drinken", es: "beber" },
    { nl: "ontkiemen", es: "brotar" },
    { nl: "uitlachen", es: "burlar" },
    { nl: "zoeken", es: "buscar" },
    { nl: "passen (kleding) | ergens in passen", es: "caber" },
    { nl: "zwijgen", es: "callar" },
    { nl: "wisselen / ruilen", es: "cambiar" },
    { nl: "zingen", es: "cantar" },
    { nl: "jagen", es: "cazar" },
    { nl: "zich borstelen", es: "cepillarse" },
    { nl: "Sluiten | dichtdoen", es: "cerrar" },
    { nl: "kletsen", es: "charlar" },
    { nl: "botsen", es: "chocar" },
    { nl: "zuigen", es: "chupar" },
    { nl: "nemen", es: "coger" },
    { nl: "kopen", es: "comprar" },
    { nl: "nakijken | controleren", es: "comprobar" },
    { nl: "besturen | rijden", es: "conducir" },
    { nl: "kennen", es: "conocer" },
    { nl: "kennismaken | ontmoeten", es: "conocerse" },
    { nl: "Antwoorden", es: "contestar" },
    { nl: "naaien", es: "coser" },
    { nl: "kosten", es: "costar" },
    { nl: "roddelen", es: "cotillear" },
    { nl: "opgroeien", es: "crecer" },
    { nl: "vinden / geloven", es: "creer" },
    { nl: "bedekken | afdekken", es: "cubrir" },
    { nl: "voldoen | vervullen | nakomen", es: "cumplir" },
    { nl: "geven", es: "dar" },
    { nl: "zeggen", es: "decir" },
    { nl: "toewijden | besteden", es: "dedicar" },
    { nl: "Spellen", es: "deletrear" },
    { nl: "ontwikkelen | uitwerken", es: "desarrollar" },
    { nl: "rusten | uitrusten", es: "descansar" },
    { nl: "ontdekken | onthullen", es: "descubrir" },
    { nl: "wensen", es: "desear" },
    { nl: "ongedaan maken", es: "deshacer" },
    { nl: "ontslaan | wegsturen", es: "despedir" },
    { nl: "afscheid nemen", es: "despedirse" },
    { nl: "ophelderen", es: "despejar" },
    { nl: "ontwaken", es: "despertarse" },
    { nl: "zich uitkleden", es: "desvestirse" },
    { nl: "teruggeven", es: "devolver" },
    { nl: "verbergen van emoties of gedachten", es: "disimular" },
    { nl: "onderscheiden", es: "distinguir" },
    { nl: "pijn hebben", es: "doler" },
    { nl: "slapen", es: "dormir" },
    { nl: "inslapen", es: "dormirse" },
    { nl: "zich douchen", es: "ducharse" },
    { nl: "verhogen | stijgen", es: "elevar" },
    { nl: "Beginnen", es: "empezar" },
    { nl: "regelen | bestellen", es: "encargar" },
    { nl: "oplichten", es: "engañar" },
    { nl: "lesgeven", es: "enseñar" },
    { nl: "begrijpen", es: "entender" },
    { nl: "Binnengaan", es: "entrar" },
    { nl: "verouderen", es: "envejecer" },
    { nl: "inpakken | inwikkelen", es: "envolver" },
    { nl: "verbergen van iets of iemand", es: "esconder" },
    { nl: "onderduiken | zich verbergen", es: "esconderse" },
    { nl: "schrijven", es: "escribir" },
    { nl: "luisteren", es: "escuchar" },
    { nl: "het stabiliseren van", es: "estabilizarse" },
    { nl: "Zijn | (hier)liggen | zich bevinden", es: "estar" },
    { nl: "niezen", es: "estornudar" },
    { nl: "studeren", es: "estudiar" },
    { nl: "verstrekken | verschaffen", es: "facilitar" },
    { nl: "falen | mislukken", es: "fallar" },
    { nl: "vertrouwen | rekenen op", es: "fiar" },
    { nl: "vaststellen | bevestigen | bepalen | fixeren", es: "fijar" },
    { nl: "zich ontwikkelen | zich vormen", es: "formarse" },
    { nl: "roken", es: "fumar" },
    { nl: "schreeuwen | roepen", es: "gritar" },
    { nl: "opslaan", es: "guardar" },
    { nl: "leuk vinden", es: "gustar" },
    { nl: "hebben", es: "haber" },
    { nl: "praten | spreken", es: "hablar" },
    { nl: "maken | doen | verrichten", es: "hacer" },
    { nl: "vleien", es: "halagar" },
    { nl: "compenseren | vergoeden", es: "indemnizar" },
    { nl: "beledigen | uitschelden", es: "insultar" },
    { nl: "uitnodigen", es: "invitar" },
    { nl: "gaan", es: "ir" },
    { nl: "zweren", es: "jurar" },
    { nl: "blaffen", es: "ladrar" },
    { nl: "wassen", es: "lavar" },
    { nl: "zich wassen", es: "lavarse" },
    { nl: "lezen", es: "leer" },
    { nl: "het opstaan", es: "levantarse" },
    { nl: "aangrenzen", es: "limitar" },
    { nl: "poetsen | zuiver maken", es: "limpiar" },
    { nl: "noemen | bellen", es: "llamar" },
    { nl: "zich noemen", es: "llamarse" },
    { nl: "meenemen | wegbrengen", es: "llevar" },
    { nl: "bereiken | realiseren | behalen", es: "lograr" },
    { nl: "vroeg opstaan", es: "madrugar" },
    { nl: "zich schminken", es: "maquillarse" },
    { nl: "miauwen", es: "maular" },
    { nl: "inbrengen | ergens insteken", es: "meter" },
    { nl: "storen | lastig vallen", es: "molestar" },
    { nl: "monteren", es: "montar" },
    { nl: "sterven | overlijden", es: "morir" },
    { nl: "zwemmen", es: "nadar" },
    { nl: "nodig hebben", es: "necesitar" },
    { nl: "gebeuren", es: "ocurrir" },
    { nl: "beledigen", es: "ofender" },
    { nl: "aanbieden", es: "ofrecer" },
    { nl: "horen", es: "oír" },
    { nl: "weglaten", es: "omitir" },
    { nl: "betalen", es: "pagar" },
    { nl: "bevallen", es: "parir" },
    { nl: "knipperen (met de ogen)", es: "parpadear" },
    { nl: "doorbrengen | passeren", es: "pasar" },
    { nl: "bestellen | Vragen (als het over een prijs,  een gunst,  of informatie gaat)", es: "pedir" },
    { nl: "zich kammen", es: "peinarse" },
    { nl: "blijven", es: "permanecer" },
    { nl: "vissen", es: "pescar" },
    { nl: "tweeten | fluiten (vogel)", es: "piar" },
    { nl: "betrappen", es: "pillar" },
    { nl: "schilderen | verven", es: "pintar" },
    { nl: "kunnen", es: "poder" },
    { nl: "Leggen | Zetten | plaatsen (to put)", es: "poner" },
    { nl: "vragen", es: "preguntar" },
    { nl: "Voorstellen | presenteren", es: "presentar" },
    { nl: "beloven", es: "prometer" },
    { nl: "liggen (plaats)", es: "quedar" },
    { nl: "klagen", es: "quejar" },
    { nl: "verbranden", es: "quemar" },
    { nl: "willen", es: "querer" },
    { nl: "weigeren | afwijzen", es: "rechazar" },
    { nl: "ontvangen", es: "recibir" },
    { nl: "ophalen | afhalen", es: "recoger" },
    { nl: "onderhandelen", es: "regatear" },
    { nl: "terugkeren", es: "regresar" },
    { nl: "Herhalen", es: "repitir" },
    { nl: "oplossen", es: "resolver" },
    { nl: "ademen", es: "respirar" },
    { nl: "Antwoorden | reageren", es: "responder" },
    { nl: "stelen | overvallen", es: "robar" },
    { nl: "breken | stuk gaan", es: "romper" },
    { nl: "snurken", es: "roncar" },
    { nl: "weten | kennen", es: "saber" },
    { nl: "uithalen | uitnemen", es: "sacar" },
    { nl: "vertrekken | weggaan | uitgaan | verschijnen | uitkomen |", es: "salir" },
    { nl: "begroeten", es: "saludar" },
    { nl: "blijven doorgaan | blijven verdergaan", es: "seguir" },
    { nl: "scheiden", es: "separar" },
    { nl: "zijn", es: "ser" },
    { nl: "zweten", es: "sudar" },
    { nl: "hebben", es: "tener" },
    { nl: "Beëindigen", es: "terminar" },
    { nl: "nemen", es: "tomar" },
    { nl: "werken", es: "trabajar" },
    { nl: "brengen", es: "traer" },
    { nl: "gebruiken", es: "utilizar" },
    { nl: "kosten", es: "valer" },
    { nl: "verkopen", es: "vender" },
    { nl: "Komen", es: "venir" },
    { nl: "zien", es: "ver" },
    { nl: "zomervakantie nemen", es: "veranear" },
    { nl: "zich aankleden", es: "vestirse" },
    { nl: "reizen", es: "viajar" },
    { nl: "bezoeken", es: "visitar" },
    { nl: "leven", es: "vivir" },
    { nl: "terugkomen | teruggaan", es: "volver" },
    { nl: "erven", es: "heredar" },
    { nl: "afwassen", es: "fregar" },
    { nl: "repareren", es: "arreglar" },
    { nl: "tekenen | schetsen", es: "dibujar" },
    { nl: "krabben | krassen", es: "rascar" },
    { nl: "duizelig maken | als iemand zeeziek wordt", es: "marear" },
    { nl: "nauwkeurig nakijken of beoordelen van iets", es: "revisar" },
    { nl: "draaien", es: "girar" },
    { nl: "herhalen", es: "repetir" },
    { nl: "een plaats verlaten", es: "marcharse" },
    { nl: "zich oriënteren", es: "orientarse" },
    { nl: "oversteken | kruisen", es: "cruzar" },
    { nl: "aanwijzingen geven | de weg wijzen", es: "dar indicaciones" },
    { nl: "invoeren | introduceren | ingeven", es: "introducir" },
    { nl: "sparen", es: "ahorrar" },
    { nl: "(be)oefenen", es: "practicar" },
    { nl: "vergeten", es: "olvidar" },
    { nl: "verzamelen | samenkomen", es: "reunir" },
    { nl: "aankomen", es: "llegar" },
    { nl: "opruimen", es: "ordenar" },
    { nl: "gaan zitten", es: "sentarse" },
    { nl: "met de hond wandelen", es: "pasear el perro" },
    { nl: "een wandeling maken", es: "pasearse" },
    { nl: "slagen | goedkeuren", es: "aprobar" },
    { nl: "hopen | wachten", es: "esperar" },
    { nl: "klimmen | stijgen | omhoog gaan | instappen | uploaden", es: "subir" },
    { nl: "winnen | verdienen", es: "ganar" },
    { nl: "dol zijn op | erg houden van | graag doen", es: "encantar" },
    { nl: "hardlopen", es: "correr" },
    { nl: "relaxen | ontspannen | chillen", es: "relajar" },
    { nl: "zich ontspannen", es: "relajarse" },
    { nl: "er veel zin in hebben", es: "morirse de ganas" },
    { nl: "spelen", es: "jugar" },
    { nl: "proberen (te maken)", es: "intentar" },
    { nl: "gewoonlijk (de gewoonte hebben)", es: "soler" },
    { nl: "organiseren", es: "organizar" },
    { nl: "spelen (een instrument)", es: "tocar (un instrumento)" },
    { nl: "zich vermaken | zich amuseren", es: "divertirse" },
    { nl: "skiën", es: "esquiar" },
    { nl: "beslissen", es: "decidir" },
    { nl: "het eens zijn", es: "estar de acuerdo" },
    { nl: "afslaan", es: "doblar" },
    { nl: "kiezen", es: "elegir" },
    { nl: "klinken", es: "sonar" },
    { nl: "proeven (eten proberen)", es: "probar" },
    { nl: "ontbijten", es: "desayunar" },
    { nl: "een tussendoortje eten", es: "almorzar" },
    { nl: "lunchen | warm eten", es: "comer" },
    { nl: "een snack eten", es: "merendar" },
    { nl: "tapas eten | hapjes eten", es: "tapear" },
    { nl: "dineren | avondeten", es: "cenar" },
    { nl: "betegelen (wand)", es: "alicatar" },
    { nl: "betegelen (vloer)", es: "solar" },
    { nl: "haten", es: "odiar" },
    { nl: "invullen", es: "rellenar" },
    { nl: "afdalen | naar beneden gaan", es: "bajar" },
    { nl: "herinneren", es: "recordar" },
    { nl: "vinden (object of plaats)", es: "encontrar" },
    { nl: "ondertekenen", es: "firmar" },
    { nl: "vertellen", es: "contar" },
    { nl: "leegmaken", es: "vaciar" },
    { nl: "schenken", es: "regalar" },
    { nl: "markeren", es: "subrayar" },
    { nl: "verbeelden", es: "imaginar" },
    { nl: "opereren", es: "operar" },
    { nl: "zich laten opereren", es: "operarse" },
    { nl: "dwars oversteken | doorkruisen", es: "atravesar" },
    { nl: "uitzetten | uitdoen (alles wat een schakelaar heeft) | doven (alles wat warmte geeft)", es: "apagar" },
    { nl: "aandoen of ontsteken van : licht electronica of vuur", es: "encender" }
];
