// Jouw vaste, centrale woordenlijst
const fixedWoordenlijst = [
    { nl: "oh | ah", es: "¡ah!" },
    { nl: "hé", es: "¡eh!" },
    { nl: "ok", es: "¡vale!" },
    { nl: "Lang niet gezien!", es: "¡Cuánto tiempo sin verte!" },
    { nl: "op hoeveel kilometer?", es: "¿A cuántos kilómetros?" },
    { nl: "om hoe laat?", es: "¿A qué hora?" },
    { nl: "nog iets?", es: "¿algo más?" },
    { nl: "Hoe heet u?", es: "¿Cómo se llama usted?" },
    { nl: "Hoe heet jij?", es: "¿Cómo te llamas?" },
    { nl: "Hoe?", es: "¿Cómo?" },
    { nl: "Wat? Welke?", es: "¿cuál?" },
    { nl: "Wanneer is jouw verjaardag?", es: "¿Cuándo es tu compleaños?" },
    { nl: "wanneer?", es: "¿cuándo?" },
    { nl: "hoeveel kosten ze?", es: "¿cuánto cuestan?" },
    { nl: "hoeveel is alles samen?", es: "¿Cuánto es todo?" },
    { nl: "hoeveel is het?", es: "¿cuánto es?" },
    { nl: "hoeveel moet ik betalen?", es: "¿cuánto tengo que pagar?" },
    { nl: "hoeveel kost het?", es: "¿cuánto vale?" },
    { nl: "hoeveel kosten ze?", es: "¿cuánto valen?" },
    { nl: "Hoeveel?", es: "¿Cuánto?" },
    { nl: "Hoeveel jaar ben jij?", es: "¿Cuántos años tienes?" },
    { nl: "VAN waar + komen ?", es: "¿DE dónde + Venir?" },
    { nl: "Waar is?", es: "¿Dónde es?" },
    { nl: "Waar zijn ze?", es: "¿Dónde están?" },
    { nl: "Waar ben je?", es: "¿Dónde estás?" },
    { nl: "Hoe kan ik u helpen?", es: "¿En qué puedo ayudarte?" },
    { nl: "wat wenst u?", es: "¿qué desea?" },
    { nl: "Welke leeftijd heb jij?", es: "¿Qué edad tienes?" },
    { nl: "wat betekent…?", es: "¿qué significa...?" },
    { nl: "hoe gaat het er mee?", es: "¿Qué tal?" },
    { nl: "Wat?", es: "¿Qué?" },
    { nl: "Wie?", es: "¿Quién?" },
    { nl: "zullen we ... nemen?", es: "¿tomamos?" },
    { nl: "Nietwaar? | toch?", es: "¿Verdad?" },
    { nl: "over (aantal)", es: "a" },
    { nl: "NAAR waar + gaan", es: "A dónde + Ir" },
    { nl: "om 7 uur ´s morgens", es: "a las siete de la mañana" },
    { nl: "in de loop van", es: "a lo largo" },
    { nl: "in de loop hiervan", es: "a lo largo de la misma" },
    { nl: "even kijken | eens kijken", es: "a ver" },
    { nl: "advocaat", es: "abogado" },
    { nl: "april", es: "Abril" },
    { nl: "ongeluk", es: "accidente" },
    { nl: "olie", es: "Aceite" },
    { nl: "accent", es: "acento" },
    { nl: "trottoir", es: "acera" },
    { nl: "dag", es: "adiós" },
    { nl: "Afrikaans", es: "africano" },
    { nl: "augustus", es: "Agosto" },
    { nl: "water", es: "agua" },
    { nl: "daar", es: "ahí" },
    { nl: "nu", es: "ahora" },
    { nl: "afzonderlijk | hier en daar", es: "aislado" },
    { nl: "knoflook", es: "ajo" },
    { nl: "in het | ten", es: "al" },
    { nl: "aan de andere kant", es: "al otro lado" },
    { nl: "vrolijk", es: "alegre | feliz" },
    { nl: "Duitsland", es: "Alemania" },
    { nl: "het tapijt | vloerkleed", es: "la alfombra" },
    { nl: "Iets", es: "Algo" },
    { nl: "Soms", es: "Alguna veses" },
    { nl: "een of ander | enkel", es: "alguno" },
    { nl: "Hoog", es: "Alto(a)" },
    { nl: "leerling", es: "alumno" },
    { nl: "Geel", es: "Amarillo" },
    { nl: "Antwerpen", es: "Amberes" },
    { nl: "een vriendin", es: "Una amiga" },
    { nl: "vriend", es: "Amigo" },
    { nl: "Liefde", es: "Amor" },
    { nl: "Amsterdam", es: "Ámsterdam" },
    { nl: "Breed", es: "Ancho(a)" },
    { nl: "jaar", es: "año" },
    { nl: "Eergisteren", es: "Anteayer" },
    { nl: "antenne", es: "antena" },
    { nl: "Vóór (in tijd)", es: "Antes" },
    { nl: "vóór de koop", es: "antes de la compra" },
    { nl: "antiek", es: "antiguo" },
    { nl: "ringvinger", es: "anular" },
    { nl: "familienaam", es: "apellido" },
    { nl: "hier", es: "aquí" },
    { nl: "Argentinië", es: "Argentina" },
    { nl: "Argentijnse", es: "argentina" },
    { nl: "artiest | kunstenaar", es: "El Artista" },
    { nl: "artieste | kunstenares", es: "La Artista" },
    { nl: "Oostenrijk", es: "Austria" },
    { nl: "bus", es: "autobús" },
    { nl: "vliegtuig", es: "avión" },
    { nl: "Gisteren", es: "Ayer" },
    { nl: "stewardess", es: "Azafata" },
    { nl: "Blauw", es: "Azul" },
    { nl: "dans", es: "baile" },
    { nl: "Laag", es: "Bajo(a)" },
    { nl: "bad", es: "baño" },
    { nl: "Goedkoop", es: "Barato(a)" },
    { nl: "boot", es: "barca ?" },
    { nl: "schip", es: "barco ?" },
    { nl: "vat ; ton", es: "barril" },
    { nl: "België", es: "Bélgica" },
    { nl: "Berlijn", es: "Berlín" },
    { nl: "Bern", es: "Berna" },
    { nl: "kus", es: "Beso" },
    { nl: "Goed", es: "Bien" },
    { nl: "welkom", es: "Bienvenidos" },
    { nl: "Bilbao", es: "Bilbao" },
    { nl: "briefje (geld)", es: "billete" },
    { nl: "Wit", es: "Blanco(a)" },
    { nl: "mond", es: "Boca" },
    { nl: "Bolivië", es: "Bolivia" },
    { nl: "fles", es: "botella" },
    { nl: "sleepnet", es: "Bou" },
    { nl: "Brazilië", es: "Brasil" },
    { nl: "Grap", es: "Broma" },
    { nl: "Brugge", es: "Brujas" },
    { nl: "Brussel", es: "Bruselas" },
    { nl: "goede reis", es: "Buen viaje" },
    { nl: "goedenavond", es: "Buenas noches" },
    { nl: "goedemiddag", es: "Buenas tardes" },
    { nl: "goedemorgen", es: "Buenos días" },
    { nl: "Beignets", es: "Buñuelos" },
    { nl: "Bruis", es: "Burbuja" },
    { nl: "Driekoningen", es: "Cabalgata de Reyes" },
    { nl: "Paard", es: "Caballo" },
    { nl: "Geit", es: "Cabra" },
    { nl: "Geitenlam", es: "Cabrito" },
    { nl: "iedere", es: "Cada" },
    { nl: "koffie | café", es: "Café" },
    { nl: "kassa | doos | kist", es: "caja" },
    { nl: "kluisje", es: "Caja de seguridad" },
    { nl: "kassier", es: "cajero" },
    { nl: "kwaliteit", es: "Calidad" },
    { nl: "heet | warm (object)", es: "caliente" },
    { nl: "straat", es: "Calle" },
    { nl: "het is warm (weer)", es: "hace calor" },
    { nl: "kaal", es: "Calvo" },
    { nl: "het bed", es: "la cama" },
    { nl: "ober", es: "Camarero" },
    { nl: "wisselgeld", es: "cambio" },
    { nl: "vrachtwagen", es: "Camión" },
    { nl: "camping", es: "camping" },
    { nl: "lied", es: "canción" },
    { nl: "Duur", es: "Caro(a)" },
    { nl: "brief", es: "Carta" },
    { nl: "huis", es: "Casa" },
    { nl: "Getrouwd", es: "Casado" },
    { nl: "bijna", es: "Casi" },
    { nl: "Bruin haar", es: "Castaño(a)" },
    { nl: "Straf", es: "Castigado" },
    { nl: "oorzaak", es: "Causa" },
    { nl: "op korte afstand", es: "Cercanía" },
    { nl: "Varken", es: "Cerdo" },
    { nl: "gesloten", es: "Cerrado" },
    { nl: "bier", es: "Cerveza" },
    { nl: "Chili", es: "Chile" },
    { nl: "chocolade", es: "Chocolate" },
    { nl: "Hert", es: "Ciervo" },
    { nl: "sigaret", es: "cigarrillo" },
    { nl: "ooievaar", es: "cigüeña" },
    { nl: "bioscoop", es: "Cine" },
    { nl: "stad", es: "Ciudad" },
    { nl: "opklaring", es: "claro" },
    { nl: "klas | les", es: "Clase" },
    { nl: "auto", es: "Coche" },
    { nl: "Vuil persoon", es: "Cochino(a)" },
    { nl: "Puppie", es: "Cochorro" },
    { nl: "verzamelaar", es: "Coleccionista" },
    { nl: "Colombia", es: "Colombia" },
    { nl: "kleur", es: "Color" },
    { nl: "klasgenoot", es: "compañero de clase" },
    { nl: "communicatie", es: "Comunicación" },
    { nl: "met", es: "con" },
    { nl: "medeklinker", es: "Consonante" },
    { nl: "Kopenhagen", es: "Copenhague" },
    { nl: "middelvinger", es: "Corazon" },
    { nl: "Schaapslam", es: "Cordero" },
    { nl: "postkantoor", es: "Correos" },
    { nl: "Kort", es: "Corto(a)" },
    { nl: "ding", es: "cosa" },
    { nl: "Costa Rica", es: "Costa Rica" },
    { nl: "Cuba", es: "Cuba" },
    { nl: "mes", es: "cuchillo" },
    { nl: "pastoor", es: "Cura" },
    { nl: "van", es: "de" },
    { nl: "'s nachts (tss 00:00 en 6:00)", es: "de la madrugada" },
    { nl: "'sAvonds", es: "De la noche" },
    { nl: "geen dank | tot uw dienst", es: "de nada" },
    { nl: "Onder", es: "Debajo de" },
    { nl: "vinger", es: "dedo" },
    { nl: "tenen", es: "dedos de los pies" },
    { nl: "van het", es: "del" },
    { nl: "voor (object)", es: "Delante de" },
    { nl: "Dolfijn", es: "Delfín" },
    { nl: "Dun", es: "Delgado(a)" },
    { nl: "teveel", es: "demasiado" },
    { nl: "te weinig", es: "demasiado poco" },
    { nl: "geeft u mij", es: "déme" },
    { nl: "de tandarts (m/v)", es: "el/la dentista" },
    { nl: "In", es: "Dentro de" },
    { nl: "binnen de E.U.", es: "Dentro de la U.E." },
    { nl: "tank", es: "depósito" },
    { nl: "vanaf", es: "desde" },
    { nl: "langzaam", es: "despacio" },
    { nl: "het is helder | onbewolkt", es: "está despejado" },
    { nl: "dan | daarna | vervolgens", es: "Después" },
    { nl: "ná de koop", es: "después de la compra" },
    { nl: "Achter de/het", es: "Detrás de" },
    { nl: "gesprek", es: "diálogo" },
    { nl: "woordenboek", es: "diccionario" },
    { nl: "december", es: "Diciembre" },
    { nl: "zegt u mij | zegt u het maar", es: "dígame" },
    { nl: "geld", es: "Dinero" },
    { nl: "Dinosaurus", es: "Dinosaurio" },
    { nl: "directeur", es: "Director" },
    { nl: "op middenlange afstand", es: "distancia media" },
    { nl: "Zondag", es: "domingo" },
    { nl: "zoet", es: "dulce" },
    { nl: "gedurende", es: "durante" },
    { nl: "Ecuador", es: "Ecuador" },
    { nl: "leeftijd", es: "edad" },
    { nl: "Gebouw", es: "Edificio" },
    { nl: "inderdaad", es: "efectivamente" },
    { nl: "de | het", es: "el" },
    { nl: "hij", es: "él" },
    { nl: "De buikspieren", es: "El abdomen" },
    { nl: "verleden jaar", es: "El año pasado" },
    { nl: "De kast", es: "El Armario" },
    { nl: "Basketbal (de sport)", es: "El baloncesto" },
    { nl: "de basketbal (de bal)", es: "la pelota de baloncesto" },
    { nl: "De bank", es: "El Banco" },
    { nl: "De handtas", es: "El Bolso" },
    { nl: "Het centrum", es: "El Centro" },
    { nl: "De hemel", es: "El cielo" },
    { nl: "Elleboog", es: "El Codo" },
    { nl: "Het continent", es: "El Continente" },
    { nl: "De Nek", es: "El Cuello" },
    { nl: "De dag", es: "El día" },
    { nl: "Het Boek", es: "El Libro" },
    { nl: "De zee", es: "El mar" },
    { nl: "De Golf van Biskaje", es: "El Mar Cantábrico" },
    { nl: "De Dokter", es: "El Médico" },
    { nl: "Het Museum", es: "El Museo" },
    { nl: "De Dij", es: "El Muslo" },
    { nl: "De Atlantische Oceaan", es: "El Océano Atlántico" },
    { nl: "Het Binnenoor", es: "El Oído" },
    { nl: "De Navel", es: "El Ombligo" },
    { nl: "De Paraplu", es: "El Paraguas" },
    { nl: "Het Gebak", es: "El Pastel" },
    { nl: "De Borst", es: "El Pecho" },
    { nl: "het haar", es: "el pelo" },
    { nl: "de penis", es: "el pene" },
    { nl: "De Herberguitbater", es: "El Posadero" },
    { nl: "de bezitter", es: "el poseedor" },
    { nl: "de volgende", es: "el próximo" },
    { nl: "De klok ; horloge", es: "El reloj" },
    { nl: "El Salvador", es: "El Salvador" },
    { nl: "de maag", es: "el stomago" },
    { nl: "De schoonvader", es: "El suegro" },
    { nl: "het krukje", es: "El taburete" },
    { nl: "de hiel", es: "el talón" },
    { nl: "Het weer | de tijd", es: "El tiempo" },
    { nl: "de enkel", es: "el tobillo" },
    { nl: "de romp", es: "el tronco" },
    { nl: "de laatste", es: "El último" },
    { nl: "Olifant", es: "Elefante" },
    { nl: "uitgiften", es: "Emisiones" },
    { nl: "bediende", es: "empleado" },
    { nl: "bij | in | op", es: "en" },
    { nl: "in het centrum", es: "en el centro" },
    { nl: "in het algemeen", es: "en general" },
    { nl: "aangename kennismaking", es: "encantado(a)" },
    { nl: "Op", es: "Encima de" },
    { nl: "januari", es: "Enero" },
    { nl: "verpleegster", es: "Enfermera" },
    { nl: "dan", es: "entonces" },
    { nl: "is", es: "es" },
    { nl: "Het is 1 uur", es: "Es la una" },
    { nl: "namelijk", es: "es que" },
    { nl: "dat is zo", es: "eso es" },
    { nl: "Spanje", es: "España" },
    { nl: "spanjaard | spaans", es: "español" },
    { nl: "Spaanse", es: "española" },
    { nl: "speciaal", es: "especial" },
    { nl: "spiegel", es: "espejo" },
    { nl: "ligt", es: "está" },
    { nl: "station", es: "estación" },
    { nl: "Verenigde Staten", es: "Estados Unidos" },
    { nl: "oosten", es: "este" },
    { nl: "dit jaar", es: "este año" },
    { nl: "stijl", es: "estilo" },
    { nl: "Stockholm", es: "Estocolmo" },
    { nl: "straat van Gibraltar", es: "Estrecho de Gibraltar" },
    { nl: "Smal", es: "Estrecho(a)" },
    { nl: "student", es: "estudiante" },
    { nl: "uitstekend", es: "estupendo" },
    { nl: "euro", es: "euro" },
    { nl: "Europa", es: "Europa" },
    { nl: "behalve", es: "excepto" },
    { nl: "ervaring", es: "experiencia" },
    { nl: "uitleg", es: "explicación" },
    { nl: "buitenland", es: "Extranjero" },
    { nl: "fantasie", es: "fantasía" },
    { nl: "februari", es: "febrero" },
    { nl: "Vrouwelijk", es: "Femenino" },
    { nl: "feest", es: "fiesta" },
    { nl: "Filipijnen", es: "Filipinas" },
    { nl: "zwak", es: "flojo" },
    { nl: "foto", es: "Foto" },
    { nl: "Frankrijk", es: "Francia" },
    { nl: "Zin", es: "Frase" },
    { nl: "zinnen", es: "frases" },
    { nl: "grens", es: "frontera" },
    { nl: "grenzen", es: "fronteras" },
    { nl: "fruit", es: "fruta" },
    { nl: "vuur", es: "Fuego" },
    { nl: "Uit", es: "Fuera de" },
    { nl: "sterk", es: "fuerte" },
    { nl: "voetbal", es: "fútbol" },
    { nl: "Haan", es: "Gallo" },
    { nl: "Gent", es: "Gante" },
    { nl: "Kat", es: "Gato" },
    { nl: "krik", es: "gato" },
    { nl: "generaal", es: "general" },
    { nl: "mensen", es: "gente" },
    { nl: "overschrijving", es: "giro" },
    { nl: "zigeuner", es: "gitano" },
    { nl: "ballon", es: "globo" },
    { nl: "dik (vet)", es: "gordo" },
    { nl: "Gorilla", es: "Gorila" },
    { nl: "Druppel", es: "Gota" },
    { nl: "dank u wel", es: "gracias" },
    { nl: "graad", es: "grado" },
    { nl: "Groot", es: "Grande" },
    { nl: "Dik", es: "Grueso(a) | Gordo" },
    { nl: "Handschoen", es: "Guante" },
    { nl: "Guatemala", es: "Guatemala" },
    { nl: "oorlog", es: "guerra" },
    { nl: "guerilla", es: "guerrilla" },
    { nl: "kiezelsteen", es: "guijarro" },
    { nl: "Equatoriaal-Guinea", es: "Guinea Ecuatorial" },
    { nl: "gitaar", es: "guitarra" },
    { nl: "de kamer", es: "la habitación" },
    { nl: "boodschappen doen", es: "hacer la compra" },
    { nl: "een examen afleggen", es: "hacer un examen" },
    { nl: "een cadeau geven", es: "hacer un regalo" },
    { nl: "op reis gaan", es: "hacer un viaje" },
    { nl: "op excursie gaan", es: "hacer una excursión" },
    { nl: "Hamburg", es: "Hamburgo" },
    { nl: "tot aan", es: "hasta" },
    { nl: "tot ziens | tot binnenkort | tot straks | tot later", es: "Hasta luego" },
    { nl: "Er is | er zijn", es: "Hay" },
    { nl: "ijsjes", es: "helados" },
    { nl: "Helikopter", es: "helicóptero" },
    { nl: "zus", es: "hermana" },
    { nl: "zusters", es: "hermanas" },
    { nl: "broer", es: "hermano" },
    { nl: "broer en zus", es: "hermanos" },
    { nl: "Gras", es: "Hierba" },
    { nl: "dochter", es: "hija" },
    { nl: "zoon", es: "hijo" },
    { nl: "kampvuur", es: "Hogueras" },
    { nl: "hallo", es: "hola" },
    { nl: "Nederland", es: "Holanda" },
    { nl: "Nederlanders", es: "Holandeses" },
    { nl: "man", es: "hombre" },
    { nl: "Honduras", es: "Honduras" },
    { nl: "hotel", es: "hotel" },
    { nl: "Vandaag", es: "Hoy" },
    { nl: "ei", es: "huevo" },
    { nl: "Iberisch", es: "Ibérica" },
    { nl: "kerk", es: "Iglesia" },
    { nl: "belangrijke", es: "importante" },
    { nl: "wijsvinger", es: "indíce" },
    { nl: "infectie", es: "infección" },
    { nl: "Engeland", es: "Inglaterra" },
    { nl: "Toiletpot", es: "Inodoro" },
    { nl: "interessant", es: "interesante" },
    { nl: "winter", es: "invierno" },
    { nl: "Italië", es: "Italia" },
    { nl: "chef", es: "jefe" },
    { nl: "sherry", es: "Jerez" },
    { nl: "Donderdag", es: "jueves" },
    { nl: "juli", es: "Julio" },
    { nl: "juni", es: "Junio" },
    { nl: "kilo", es: "kilo" },
    { nl: "kilometer", es: "kilómetro" },
    { nl: "De douane", es: "La aduana" },
    { nl: "De korte wijzer (klok)", es: "La aguja corta" },
    { nl: "De lange wijzer (klok)", es: "La aguja larga" },
    { nl: "architectuur", es: "la arquitectura" },
    { nl: "De autosnelweg", es: "La autopista" },
    { nl: "de oksel", es: "la axila" },
    { nl: "de kin", es: "la barbilla" },
    { nl: "de buik", es: "la bariga" },
    { nl: "De vuilbak", es: "La Basura" },
    { nl: "de mond", es: "la boca" },
    { nl: "het huwelijk", es: "La boda" },
    { nl: "De zak", es: "La Bolsa" },
    { nl: "het hoofd", es: "La cabeza" },
    { nl: "de heup", es: "la cadera" },
    { nl: "De hoofdstad", es: "La capital" },
    { nl: "het gezicht", es: "la cara" },
    { nl: "De (nationale) hoofdweg", es: "La carretera nacional" },
    { nl: "de wenkbrouwen", es: "la cejas" },
    { nl: "de taille", es: "la centura" },
    { nl: "de mand", es: "La cesta" },
    { nl: "De zwemles", es: "La clase de natación" },
    { nl: "Het eten", es: "La comida" },
    { nl: "De rekening", es: "La cuenta" },
    { nl: "de rug", es: "la espalda" },
    { nl: "Het benzinestation met garage", es: "La estación de servicio" },
    { nl: "het voorhoofd", es: "la frente" },
    { nl: "De grens", es: "La frontera" },
    { nl: "De benzine", es: "La gasolina" },
    { nl: "Het benzinestation", es: "La gasolinera" },
    { nl: "De dochter", es: "La hija" },
    { nl: "Het uur", es: "La hora" },
    { nl: "Het bedrijf", es: "La impresa" },
    { nl: "Het eiland", es: "La isla" },
    { nl: "het grootste gedeelte", es: "la mayor parte" },
    { nl: "de schommelstoel", es: "La mecedora" },
    { nl: "de pols", es: "la muñeca" },
    { nl: "de bil", es: "la naiga" },
    { nl: "de neus", es: "la nariz" },
    { nl: "de kuit", es: "la pantorilla" },
    { nl: "de pruik", es: "la peluca" },
    { nl: "De Herberg", es: "La Posada" },
    { nl: "De herberguitbaatster", es: "La Posadera" },
    { nl: "Het antwoord", es: "La respuesta" },
    { nl: "de knie", es: "la rodilla" },
    { nl: "Vorige week", es: "La semana pasada" },
    { nl: "Volgende week", es: "La semana que viene" },
    { nl: "De parasol", es: "La sombrilla" },
    { nl: "schoonmoeder", es: "La suegra" },
    { nl: "de (kleding)maat", es: "la talla" },
    { nl: "de televisie", es: "la televisión" },
    { nl: "de theorie", es: "la teoría" },
    { nl: "de tiet", es: "la teta" },
    { nl: "De theepot", es: "La tetera" },
    { nl: "De Eiffeltoren", es: "La Torre Eiffel" },
    { nl: "De ligstoel", es: "La tumbona" },
    { nl: "de vagina", es: "la vulva" },
    { nl: "de hand", es: "la mano" },
    { nl: "de handen", es: "las manos" },
    { nl: "lip", es: "labio" },
    { nl: "Dief", es: "Ladrón" },
    { nl: "Potloden", es: "Lapices" },
    { nl: "Potlood", es: "Lápiz" },
    { nl: "Lang", es: "Largo(a)" },
    { nl: "De Balearen", es: "Las Baleares" },
    { nl: "de ledematen", es: "las extremidades" },
    { nl: "de vormen", es: "las formas" },
    { nl: "De bril", es: "Las gafas" },
    { nl: "de ideeën", es: "las ideas" },
    { nl: "de wangen", es: "las mejillas" },
    { nl: "de billen", es: "las nalgas" },
    { nl: "de oren", es: "las orejas" },
    { nl: "de wimpers", es: "las pestañas" },
    { nl: "de benen", es: "las piernas" },
    { nl: "les", es: "lección" },
    { nl: "melk", es: "leche" },
    { nl: "de sla | de kropsla", es: "la lechuga" },
    { nl: "op verre afstand", es: "Lejanía" },
    { nl: "taal", es: "lengua" },
    { nl: "Leeuw", es: "León" },
    { nl: "Letters", es: "Letras" },
    { nl: "vrij", es: "libre" },
    { nl: "Luik", es: "Lieja" },
    { nl: "Lissabon", es: "Lisboa" },
    { nl: "liter", es: "litro" },
    { nl: "sleutel", es: "llave" },
    { nl: "vol", es: "lleno" },
    { nl: "de regen", es: "la lluvia" },
    { nl: "ik begrijp het", es: "lo entiendo" },
    { nl: "Hetzelfde", es: "Lo mismo" },
    { nl: "logisch", es: "lógico" },
    { nl: "Londen", es: "Londres" },
    { nl: "de armen", es: "los brazos" },
    { nl: "de afbeeldingen", es: "los cuadros" },
    { nl: "de vingers", es: "los dedos" },
    { nl: "de tanden", es: "los dientes" },
    { nl: "de schouders", es: "los hombros" },
    { nl: "de lippen", es: "los labios" },
    { nl: "de materialen", es: "los materiales" },
    { nl: "De nummers (getallen)", es: "Los números" },
    { nl: "de ogen", es: "los ojos" },
    { nl: "de oogleden", es: "los párpados" },
    { nl: "de borsten", es: "los pechos" },
    { nl: "de voeten", es: "los pies" },
    { nl: "de bezittelijke voornaamwoorden", es: "los posesivos" },
    { nl: "de testikels ; teelballen", es: "los testículos" },
    { nl: "Leuven", es: "Lovaina" },
    { nl: "plaats", es: "Lugar" },
    { nl: "Maandag", es: "Lunes" },
    { nl: "moeder", es: "Madre" },
    { nl: "Vroeg opstaan", es: "Madrugar" },
    { nl: "koffer", es: "maleta" },
    { nl: "Mechelen", es: "Malinas" },
    { nl: "slecht", es: "malo" },
    { nl: "Morgen", es: "Mañana" },
    { nl: "Morgenvroeg", es: "Mañana por la mañana" },
    { nl: "Morgenavond", es: "Mañana por la noche" },
    { nl: "Morgenmiddag", es: "Mañana por la tarde" },
    { nl: "Middellandse Zee", es: "Mar Mediterráneo" },
    { nl: "man | echtgenoot", es: "Marido" },
    { nl: "Vlinder", es: "Mariposa" },
    { nl: "Bruin", es: "Marrón" },
    { nl: "Dinsdag", es: "Martes" },
    { nl: "maart", es: "Marzo" },
    { nl: "sneller", es: "más rápido" },
    { nl: "Huisdier", es: "Mascota" },
    { nl: "Mannelijk", es: "Masculino" },
    { nl: "maximum", es: "máximo" },
    { nl: "Mei", es: "Mayo" },
    { nl: "Grootste | beste", es: "mayor" },
    { nl: "ze noemen mij", es: "me llaman" },
    { nl: "ik heet", es: "me llamo" },
    { nl: "monteur", es: "mecánico" },
    { nl: "12u 'snachts", es: "Medianoche" },
    { nl: "geneeskunde", es: "medicina" },
    { nl: "'s middags", es: "Mediodía" },
    { nl: "pink", es: "meñique" },
    { nl: "markt", es: "mercado" },
    { nl: "de tafel", es: "la mesa" },
    { nl: "metro", es: "metro" },
    { nl: "Mexico", es: "México" },
    { nl: "mijn", es: "Mi" },
    { nl: "Woensdag", es: "Miércoles" },
    { nl: "militair", es: "militar" },
    { nl: "minimum", es: "mínimo" },
    { nl: "mode", es: "Moda" },
    { nl: "matig", es: "moderado" },
    { nl: "gebakje", es: "Mona" },
    { nl: "Aap", es: "Mono" },
    { nl: "moto", es: "motocicleta" },
    { nl: "hartelijk bedankt | dank u wel", es: "muchas gracias" },
    { nl: "veel", es: "mucho" },
    { nl: "leuk je te ontmoeten", es: "mucho gusto" },
    { nl: "vrouw", es: "mujer" },
    { nl: "(geld)boete", es: "multa" },
    { nl: "Munchen", es: "Múnich" },
    { nl: "muziek", es: "música" },
    { nl: "erg", es: "muy" },
    { nl: "erg goed | goed zo", es: "muy bien" },
    { nl: "niets", es: "nada" },
    { nl: "Oranje", es: "el naranja" },
    { nl: "Natuur", es: "Naturaleza" },
    { nl: "Zwart", es: "Negro" },
    { nl: "Nicaragua", es: "Nicaragua" },
    { nl: "mist", es: "niebla" },
    { nl: "Kleindochter", es: "Nieta" },
    { nl: "Kleinzoon", es: "Nieto" },
    { nl: "de sneeuw", es: "la nieve" },
    { nl: "jongen | kind", es: "niño" },
    { nl: "Kinderen", es: "Niños" },
    { nl: "neen | niet | geen", es: "no" },
    { nl: "naam", es: "nombre" },
    { nl: "normale benzine", es: "normal" },
    { nl: "noorden", es: "norte" },
    { nl: "november", es: "Noviembre" },
    { nl: "verloofde", es: "novio" },
    { nl: "wolk", es: "nube" },
    { nl: "het is bewolkt", es: "está nublado" },
    { nl: "of", es: "o" },
    { nl: "objecten", es: "objetos" },
    { nl: "oktober", es: "Octubre" },
    { nl: "westen", es: "oeste" },
    { nl: "officieel", es: "oficial" },
    { nl: "kantoor", es: "oficina" },
    { nl: "luistert u eens | pardon", es: "oiga" },
    { nl: "Golf (zee)", es: "Ola" },
    { nl: "Beer", es: "Oso" },
    { nl: "Oostende", es: "Ostende" },
    { nl: "nog twee", es: "otras dos" },
    { nl: "Schaap", es: "Oveja" },
    { nl: "vader", es: "padre" },
    { nl: "Stiefvader", es: "Padre potativo" },
    { nl: "land", es: "país" },
    { nl: "landen", es: "países" },
    { nl: "Vogel", es: "Pájaro" },
    { nl: "woorden", es: "palabras" },
    { nl: "brood", es: "pan" },
    { nl: "Panama", es: "Panamá" },
    { nl: "zakdoek", es: "pañuelo" },
    { nl: "papier", es: "papel" },
    { nl: "paar", es: "par" },
    { nl: "voor", es: "para" },
    { nl: "Paraguay", es: "Paraguay" },
    { nl: "Muur", es: "Pared" },
    { nl: "een koppel | een paar | een stel", es: "una pareja" },
    { nl: "Parijs", es: "París" },
    { nl: "Het park", es: "El parque" },
    { nl: "passeert", es: "pasa" },
    { nl: "Overmorgen", es: "Pasada Mañana" },
    { nl: "paspoort", es: "pasaporte" },
    { nl: "aardappel", es: "patata" },
    { nl: "Eend", es: "Pato" },
    { nl: "Bestelling", es: "Pedido" },
    { nl: "filmen", es: "películas" },
    { nl: "ros", es: "Pelirrojo(a)" },
    { nl: "kapper", es: "peluquero" },
    { nl: "schiereiland", es: "Península" },
    { nl: "Klein", es: "Pequeño(a)" },
    { nl: "sorry", es: "perdón" },
    { nl: "journalist", es: "el periodista" },
    { nl: "journaliste", es: "la periodista" },
    { nl: "maar", es: "Pero" },
    { nl: "Hond", es: "Perro" },
    { nl: "personen", es: "personas" },
    { nl: "vooruitzicht", es: "perspectiva" },
    { nl: "Peru", es: "Perú" },
    { nl: "gewicht", es: "peso" },
    { nl: "pianist(e)", es: "pianista" },
    { nl: "batterij", es: "pila" },
    { nl: "ananas", es: "piña" },
    { nl: "schilder", es: "pintor" },
    { nl: "Pyreneeën", es: "Pirineos" },
    { nl: "Schoolbord", es: "Pizarra" },
    { nl: "Meervoud", es: "Plural" },
    { nl: "Arm (geld)", es: "Pobres" },
    { nl: "weinig | niet veel", es: "poco" },
    { nl: "Kip", es: "Pollo" },
    { nl: "geeft u mij", es: "póngame" },
    { nl: "via | door | per", es: "por" },
    { nl: "alstublieft", es: "por favor" },
    { nl: "eindelijk", es: "por fin" },
    { nl: "´s morgens", es: "por la mañana" },
    { nl: "´s avonds", es: "por la noche" },
    { nl: "´s middags", es: "por la tarde" },
    { nl: "natuurlijk | zeker", es: "por supuesto" },
    { nl: "Portugal", es: "Portugal" },
    { nl: "mogelijkheid", es: "posibilidad" },
    { nl: "Praag", es: "Praga" },
    { nl: "neerslag", es: "precipitación" },
    { nl: "vraag", es: "pregunta" },
    { nl: "presentator", es: "presentador" },
    { nl: "iemand voorstellen", es: "presentarle" },
    { nl: "president", es: "presidente" },
    { nl: "lente", es: "primavera" },
    { nl: "beroep", es: "profesión" },
    { nl: "voorspelling", es: "pronóstico" },
    { nl: "(juridische) eigenaar", es: "propietario(a)" },
    { nl: "dorp", es: "pueblo" },
    { nl: "kunt u", es: "puede usted" },
    { nl: "Puerto Rico", es: "Puerto Rico" },
    { nl: "wel | nou | dus | tja | eh", es: "pues" },
    { nl: "duim", es: "pulgar" },
    { nl: "Paars", es: "Púrpera" },
    { nl: "dat", es: "que" },
    { nl: "kaas", es: "queso" },
    { nl: "kiosk", es: "quiosco" },
    { nl: "misschien", es: "quizás" },
    { nl: "snel", es: "rápido" },
    { nl: "Muis", es: "Ratón" },
    { nl: "Recept | doktersvoorschrift", es: "Receta" },
    { nl: "cadeautje", es: "regalo" },
    { nl: "regio | streek", es: "región" },
    { nl: "vertegenwoordiger", es: "representante" },
    { nl: "Domenicaanse Republiek", es: "República Domenicana" },
    { nl: "rest", es: "resto" },
    { nl: "tijdschrift", es: "revista" },
    { nl: "Rood", es: "Rojo" },
    { nl: "Rome", es: "Roma" },
    { nl: "rum", es: "ron" },
    { nl: "Roze", es: "el rosa" },
    { nl: "Rotterdam", es: "Roterdam" },
    { nl: "blond", es: "Rubio(a)" },
    { nl: "lawaai", es: "ruido" },
    { nl: "Zaterdag", es: "sabado" },
    { nl: "gezondheid", es: "salud" },
    { nl: "begroeting", es: "saludo" },
    { nl: "Sint Niklaas", es: "San Nicolás" },
    { nl: "watermeloen", es: "sandía" },
    { nl: "gezond", es: "sano" },
    { nl: "secretaresse", es: "secretaria" },
    { nl: "volgens", es: "según" },
    { nl: "postzegel", es: "sello" },
    { nl: "Week", es: "Semana" },
    { nl: "Oude persoon", es: "Senior joven" },
    { nl: "Mijnheer", es: "señor" },
    { nl: "dames en heren", es: "señores" },
    { nl: "zitten gaan", es: "sentarse" },
    { nl: "September", es: "Septiembre" },
    { nl: "Slang", es: "Serpiente" },
    { nl: "afdeling Filatelie", es: "Servicio Filatélico" },
    { nl: "als | indien", es: "si" },
    { nl: "ja", es: "sí" },
    { nl: "gaat u zitten", es: "siéntese" },
    { nl: "gebergte", es: "sierra" },
    { nl: "zonder", es: "sin" },
    { nl: "Enkelvoud", es: "Singular" },
    { nl: "op | rond (tijd)", es: "sobre" },
    { nl: "zon", es: "sol" },
    { nl: "vrijgezel", es: "soltero(a)" },
    { nl: "Het is ... uur", es: "Son las ..." },
    { nl: "ben ik", es: "soy yo" },
    { nl: "vloer", es: "suelo" },
    { nl: "superbenzine", es: "súper" },
    { nl: "zuiden", es: "sur" },
    { nl: "ook", es: "también" },
    { nl: "tango", es: "tango" },
    { nl: "kaart", es: "tarjeta" },
    { nl: "theater", es: "teatro" },
    { nl: "technieken", es: "técnicas" },
    { nl: "telefoon", es: "teléfono" },
    { nl: "temperatuur", es: "temperatura" },
    { nl: "alstublieft", es: "tenga" },
    { nl: "tennis", es: "tenis" },
    { nl: "Senioren (+65)", es: "Tercera edad" },
    { nl: "tekst", es: "texto" },
    { nl: "tante", es: "tía" },
    { nl: "Haai", es: "Tibúron" },
    { nl: "Tijger", es: "Tigre" },
    { nl: "oom", es: "tío" },
    { nl: "type", es: "tipo" },
    { nl: "Pietje precies | kieskeurig | autistisch", es: "Tiquismiquis" },
    { nl: "nog steeds | altijd", es: "todavía" },
    { nl: "alles", es: "todo" },
    { nl: "tomaat", es: "tomate" },
    { nl: "Stier", es: "Toro" },
    { nl: "vertaling", es: "traducción" },
    { nl: "verkeer", es: "tráfico" },
    { nl: "trein", es: "tren" },
    { nl: "toerist", es: "el turista" },
    { nl: "toeriste", es: "la turista" },
    { nl: "Een gegeven", es: "Un dato" },
    { nl: "een reportage", es: "un reportaje" },
    { nl: "Uruguay", es: "Uruguay" },
    { nl: "sociale gebruiken", es: "usos sociales" },
    { nl: "u", es: "usted" },
    { nl: "de druif", es: "la uva" },
    { nl: "Koe", es: "Vaca" },
    { nl: "vakantie", es: "vacacion" },
    { nl: "leeg", es: "vacío" },
    { nl: "buurvrouw", es: "vecina" },
    { nl: "buurman", es: "vecino" },
    { nl: "verkoper", es: "vendedor" },
    { nl: "Venezuela", es: "Venezuela" },
    { nl: "loket", es: "ventanilla" },
    { nl: "zomer", es: "verano" },
    { nl: "Groen", es: "Verde" },
    { nl: "groenten", es: "verduras" },
    { nl: "schaamte", es: "vergüenza" },
    { nl: "dierenarts", es: "veterenario" },
    { nl: "keer", es: "vez" },
    { nl: "reis", es: "viaje" },
    { nl: "Wenen", es: "Viena" },
    { nl: "de wind", es: "el viento" },
    { nl: "Vrijdag", es: "Viernes" },
    { nl: "wijn", es: "vino" },
    { nl: "zicht", es: "visibilidad" },
    { nl: "bezoek", es: "visita" },
    { nl: "weduwe", es: "viuda" },
    { nl: "weduwnaar", es: "viudo" },
    { nl: "klinker", es: "Vocal" },
    { nl: "wisselgeld", es: "vuelta" },
    { nl: "en", es: "y" },
    { nl: "en nu", es: "y ahora" },
    { nl: "al", es: "ya" },
    { nl: "Schoenwinkel", es: "Zapatería" },
    { nl: "bang ; angst", es: "miedo" },
    { nl: "smakeloos", es: "cursi" },
    { nl: "bovendien", es: "además" },
    { nl: "jaloesie", es: "celos" },
    { nl: "bebloed", es: "ensangrentado(a)" },
    { nl: "puppy", es: "cachorro" },
    { nl: "voordelen", es: "ventajas" },
    { nl: "nadelen", es: "inconvenientes" },
    { nl: "allergie", es: "alergia" },
    { nl: "pad (dier)", es: "sapo" },
    { nl: "forel", es: "trucha" },
    { nl: "een beetje tijd", es: "un rato" },
    { nl: "leugen ; niet waar", es: "mentira" },
    { nl: "Het rolgordijn ; de rolluik", es: "la persiana" },
    { nl: "maat van een object", es: "tamaño" },
    { nl: "gedane deal ; het is rond", es: "trato hecho" },
    { nl: "een familielid", es: "un pariente" },
    { nl: "hoewel ; ondanks", es: "aunque" },
    { nl: "tekening van lijnen", es: "dibujo" },
    { nl: "in het zweet staan ; zweten", es: "sudando" },
    { nl: "wasmachine", es: "lavadora" },
    { nl: "vaatwasser", es: "lavavajillas" },
    { nl: "kapot", es: "roto" },
    { nl: "de koelkast", es: "la nevera ; el frigorifico" },
    { nl: "potloodslijper", es: "sacapuntas" },
    { nl: "kurkentrekker", es: "sacacorchos" },
    { nl: "blikopener", es: "abrelatas" },
    { nl: "puntzak voor snoep", es: "cucurucho" },
    { nl: "het kan niet gemaakt worden", es: "no tiene arreglo" },
    { nl: "de hondenvanger", es: "el perrero" },
    { nl: "stinkend | onaangename geur", es: "maloliente" },
    { nl: "Darts", es: "Dardos" },
    { nl: "kerstavond", es: "Nochebuena" },
    { nl: "oevers", es: "orillas" },
    { nl: "gebouw", es: "edificio" },
    { nl: "betonklinkers ; kasseien", es: "adoquines" },
    { nl: "nat", es: "mojado(a)" },
    { nl: "slank", es: "esbelto" },
    { nl: "eigenaar (voorwerpen)", es: "dueño" },
    { nl: "zo", es: "tan" },
    { nl: "jammer", es: "pena" },
    { nl: "een goede daad", es: "un acto piadoso" },
    { nl: "pijnlijk", es: "doloroso" },
    { nl: "het schot", es: "el disparo" },
    { nl: "zijden kussens", es: "cojines de seda" },
    { nl: "perzische tapijten", es: "alfombras persas" },
    { nl: "bestelling", es: "pedido" },
    { nl: "beleefdheid", es: "cortesía" },
    { nl: "draai", es: "gire" },
    { nl: "hongerig", es: "hambriento(a)" },
    { nl: "dorstig", es: "sediento(a)" },
    { nl: "de honger", es: "el hambre" },
    { nl: "de dorst", es: "la sed" },
    { nl: "moe", es: "cansado(a)" },
    { nl: "bezorgd", es: "preocupado(a)" },
    { nl: "ziek", es: "enfermo(a)" },
    { nl: "boos", es: "enfadado(a)" },
    { nl: "de nicht (de dochter van je tante of nonkel)", es: "la prima" },
    { nl: "de neef (de zoon van je tante of nonkel)", es: "el primo" },
    { nl: "gescheiden", es: "divorciados" },
    { nl: "kleine letter", es: "minúscula" },
    { nl: "hoofdletter", es: "mayúscula" },
    { nl: "midweek | doordeweeks | tijdens de week", es: "entre semana" },
    { nl: "weekend", es: "fin de semana" },
    { nl: "een kom", es: "un bol de" },
    { nl: "de soep", es: "la sopa" },
    { nl: "de warme chocolademelk", es: "el chocolate caliente" },
    { nl: "het zebrapad | oversteekplaats voor voetgangers", es: "el paso de peatones" },
    { nl: "draaien | roteren | wenden | keren", es: "girar" },
    { nl: "ver | ver weg", es: "lejos" },
    { nl: "vlucht", es: "vuelo" },
    { nl: "als tweede", es: "de segundo" },
    { nl: "als eerste", es: "de primero" },
    { nl: "nul", es: "Cero" },
    { nl: "één", es: "uno(a) | un" },
    { nl: "twee", es: "dos" },
    { nl: "drie", es: "Tres" },
    { nl: "vier", es: "Cuatro" },
    { nl: "Vijf", es: "Cinco" },
    { nl: "zes", es: "seis" },
    { nl: "zeven", es: "siete" },
    { nl: "acht", es: "ocho" },
    { nl: "negen", es: "nueve" },
    { nl: "tien", es: "diez" },
    { nl: "elf", es: "once" },
    { nl: "twaalf", es: "doce" },
    { nl: "dertien", es: "trece" },
    { nl: "veertien", es: "Catorce" },
    { nl: "vijftien", es: "quince" },
    { nl: "zestien", es: "dieciseis" },
    { nl: "zeventien", es: "diecisiete" },
    { nl: "achttien", es: "dieciocho" },
    { nl: "negentien", es: "diecinueve" },
    { nl: "twintig | 20", es: "veinte" },
    { nl: "éénentwintig | 21", es: "veintiuno" },
    { nl: "tweeéntwintig | 22", es: "veintidós" },
    { nl: "drieëntwintig | 23", es: "veintitrés" },
    { nl: "vierentwintig | 24", es: "veinticuatro" },
    { nl: "vijfentwintig | 25", es: "veinticinco" },
    { nl: "zesentwintig | 26", es: "veintiséis" },
    { nl: "zevenentwintig |27", es: "veintisiete" },
    { nl: "achtentwintig |28", es: "veintiocho" },
    { nl: "negenentwintig |29", es: "veintinueve" },
    { nl: "dertig | 30", es: "treinta" },
    { nl: "éénendertig | 31", es: "treinta y uno" },
    { nl: "tweeëndertig | 32", es: "treinta y dos" },
    { nl: "vijfendertig | 35", es: "treinta y cinco" },
    { nl: "veertig | 40", es: "cuarenta" },
    { nl: "vijftig | 50", es: "cincuenta" },
    { nl: "zestig | 60", es: "sesenta" },
    { nl: "zeventig | 70", es: "setenta" },
    { nl: "tachtig | 80", es: "ochenta" },
    { nl: "vijfentachtig | 85", es: "ochenta y cinco" },
    { nl: "negentig | 90", es: "noventa" },
    { nl: "honderd | 100", es: "Cien" },
    { nl: "tweehonderd | 200", es: "doscientos" },
    { nl: "driehonderd | 300", es: "trescientos" },
    { nl: "vierhonderd | 400", es: "Cuatrocientos" },
    { nl: "vijfhonderd | 500", es: "quinientos" },
    { nl: "zeshonderd |600", es: "seiscientos" },
    { nl: "zevenhonderd | 700", es: "setecientos" },
    { nl: "achthonderd | 800", es: "ochocientos(as)" },
    { nl: "negenhonderd | 900", es: "novecientos" },
    { nl: "duizend | 1000", es: "Mil" },
    { nl: "een miljoen | 1000000", es: "un millón" },
    { nl: "98634", es: "Noventa y ocho mil seiscientos treinta y cuatro" },
    { nl: "rangtelwoorden", es: "ordinales" },
    { nl: "Hoofdtelwoorden", es: "Numerales cardinales" },
    { nl: "Eerste", es: "Primero(a)" },
    { nl: "Tweede", es: "Segundo(a)" },
    { nl: "Derde", es: "Tercero(a)" },
    { nl: "vierde", es: "Cuarto(a)" },
    { nl: "Vijfde", es: "Quinto(a)" },
    { nl: "zesde", es: "sexto(a)" },
    { nl: "zevende", es: "séptimo(a)" },
    { nl: "achtste", es: "octavo(a)" },
    { nl: "negende", es: "noveno(a)" },
    { nl: "tiende", es: "décimo(a)" },
    { nl: "elfde", es: "undécimo(a) | decimoprimero(a)" },
    { nl: "twaalfde", es: "duodécimo(a) | decimosegundo(a)" },
    { nl: "dertiende", es: "decimotercero(a)" },
    { nl: "veertiende", es: "decimocuarto(a)" },
    { nl: "vijftiende", es: "decimoquinto(a)" },
    { nl: "zestiende", es: "decimosexto(a)" },
    { nl: "zeventiende", es: "decimoséptimo(a)" },
    { nl: "achttiende", es: "decimoctavo(a)" },
    { nl: "negentiende", es: "decimonoveno(a)" },
    { nl: "twintigste", es: "vigésimo(a)" },
    { nl: "achttienhonderd eenenzeventig", es: "mil ochocientos setenta y uno" },
    { nl: "negentien negentig", es: "mil novecientos noventa" },
    { nl: "tweeduizendvier", es: "dos mil cuatro" },
    { nl: "tweeduizend eenentwintig", es: "dos mil veintiuno" },
    { nl: "de 21e eeuw", es: "el siglo XXI" },
    { nl: "de dochter van je broer of zus | nicht", es: "La sobrina" },
    { nl: "de zoon van je broer of zus | neef", es: "El sobrino" },
    { nl: "een oudere zus", es: "una hermana mayor" },
    { nl: "een jongere broer", es: "un hermano menor" },
    { nl: "hij is zeer lelijk", es: "es muy feo" },
    { nl: "zij is zeer lelijk", es: "es muy fea" },
    { nl: "hij is zeer knap", es: "�l es muy guapo" },
    { nl: "zij is zeer knap", es: "ella es muy guapa" },
    { nl: "een beetje mollig | een beetje dik", es: "un poco gordito" },
    { nl: "ik ben vrij klein | Ik ben nogal klein", es: "Soy bastante baja" },
    { nl: "misschien", es: "quizá" },
    { nl: "corpulent | gezet | zwaarlijvig", es: "corpulento" },
    { nl: "veranderd", es: "cambiada" },
    { nl: "atleten", es: "deportistas" },
    { nl: "glimlachend", es: "sonriente" },
    { nl: "arbeider | werknemer | werkman | werker", es: "trabajador" },
    { nl: "sympathiek", es: "simpático(a)" },
    { nl: "moedig | dapper", es: "valiente" },
    { nl: "leuk | grappig | vermakelijk | plezierig", es: "divertido(a)" },
    { nl: "geanimeerd | levendig | bruisend | vrolijk", es: "animados" },
    { nl: "georganiseerd | geregeld | geordend | overzichtelijk | gepland", es: "organizado" },
    { nl: "wanordelijk | rommelig | ongeorganiseerd", es: "desordenados" },
    { nl: "verlegen | timide | schuchter | terughoudend", es: "tímido" },
    { nl: "pessimist", es: "pesimista" },
    { nl: "leergierig | geleerde | studiebol | wetenschapper", es: "estudioso" },
    { nl: "lui | luie", es: "perezoso(a)" },
    { nl: "geordend | netjes | opgeruimd | gesorteerd", es: "ordenado" },
    { nl: "blij", es: "contento" },
    { nl: "triest | verdrietig | bedroefd", es: "triste" },
    { nl: "koppig | stijfkoppig | eigenwijs | halsstarrig", es: "testarudo" },
    { nl: "boekhouder | accountant", es: "contable" },
    { nl: "intelligent | geniaal", es: "inteligente" },
    { nl: "nerveus | zenuwachtig", es: "nervioso" },
    { nl: "de sportzaal | de fitnessruimte", es: "el gimnasio" },
    { nl: "Het is mooi weer", es: "hace buen tiempo" },
    { nl: "genereus | vrijgevig | Grootmoedig", es: "generoso(a)" },
    { nl: "vertel me", es: "cuéntame" },
    { nl: "de sport", es: "el deporte" },
    { nl: "de anderen | de rest | de overigen", es: "los demás" },
    { nl: "vroeg", es: "temprano" },
    { nl: "meteen | onmiddellijk | direct | zo terug", es: "enseguida" },
    { nl: "haakjes", es: "paréntesis" },
    { nl: "de kermis", es: "la feria" },
    { nl: "geroosterd brood | toast", es: "tostadas" },
    { nl: "de boter", es: "la mantequilla" },
    { nl: "dikwijls | vaak", es: "a menudo" },
    { nl: "het broodje", es: "el bocadillo" },
    { nl: "leren | van leer", es: "de cuero" },
    { nl: "Afgekorte woorden", es: "Palabras abreviadas" },
    { nl: "prins", es: "príncipe​" },
    { nl: "prinses", es: "princesa" },
    { nl: "koning", es: "rey" },
    { nl: "koningin", es: "reina" },
    { nl: "acteur", es: "actor" },
    { nl: "actrice", es: "actriz" },
    { nl: "priester", es: "sacerdote" },
    { nl: "priesteres", es: "sacerdotisa" },
    { nl: "het onderwerp", es: "el tema" },
    { nl: "het probleem", es: "el problema" },
    { nl: "het systeem", es: "el sistema" },
    { nl: "de taal", es: "el idioma" },
    { nl: "de planeet", es: "el planeta" },
    { nl: "de kaart", es: "el mapa" },
    { nl: "violet", es: "el violeta" },
    { nl: "de discotheek", es: "la disscoteca" },
    { nl: "doodmoe", es: "agotado(a)(s)" },
    { nl: "handbal", es: "balonmano" },
    { nl: "sorry | het spijt me", es: "lo siento" },
    { nl: "de wijk | de buurt", es: "el barrio" },
    { nl: "de bakkerij", es: "la panadería" },
    { nl: "de aardbei", es: "la fresa" },
    { nl: "de tuin", es: "el jardín" },
    { nl: "de woonkamer", es: "el salón" },
    { nl: "de badkamer", es: "el cuarto de baño" },
    { nl: "de keuken", es: "la cocina" },
    { nl: "de flat | het appartement", es: "el piso" },
    { nl: "de gang", es: "el pasillo" },
    { nl: "het raam | de venster", es: "la ventana" },
    { nl: "de bureaukamer", es: "el despacho" },
    { nl: "het berghok | de bergruimte | de berging | de rommelkamer", es: "el trastero" },
    { nl: "de prijs", es: "el precio" },
    { nl: "de lamp", es: "la lámpara" },
    { nl: "het meubel", es: "el mueble" },
    { nl: "de matras", es: "el colchón" },
    { nl: "de stoel", es: "la silla" },
    { nl: "de rek | boekenplank", es: "la estantería" },
    { nl: "de zetel", es: "la sofá" },
    { nl: "een tweepersoonsbed", es: "una cama de matrimonio" },
    { nl: "het nachtkastje", es: "La mesilla de noche" },
    { nl: "naast", es: "Al lado de" },
    { nl: "tussen", es: "entre" },
    { nl: "links van", es: "A la izquierda de" },
    { nl: "rechts van", es: "A la derecha de" },
    { nl: "de bureautafel", es: "el escritorio" },
    { nl: "comfortabel", es: "cómodo(a)" },
    { nl: "de logeerkamer", es: "la habitación de invitados" },
    { nl: "een slaapbank | zetelbed", es: "Un sofá-cama" },
    { nl: "heel gemakkelijk", es: "muy fácilmente" },
    { nl: "vrij | nogal | behoorlijk | best wel", es: "bastante" },
    { nl: "dichtbij | in de buurt van", es: "cerca" },
    { nl: "de fauteuil | een grote comfortabele stoel (met armleuningen)", es: "el sillón" },
    { nl: "de trap", es: "la escalera" },
    { nl: "de brug", es: "el puente" },
    { nl: "De stadsranden | buitenwijken", es: "las afueras" },
    { nl: "tegenover", es: "enfrente" },
    { nl: "luxe | van luxe", es: "de lujo" },
    { nl: "rechtdoor", es: "todo recto" },
    { nl: "gemeentehuis | stadhuis", es: "el ayuntamiento" },
    { nl: "nieuw", es: "nuevo(a)" },
    { nl: "oud", es: "viejo(a)" },
    { nl: "hierachter | achter", es: "detrás" },
    { nl: "de fontein | bron", es: "la fuente" },
    { nl: "een wandeling maken | gaan wandelen", es: "dar un paseo" },
    { nl: "gepast", es: "adecuada" },
    { nl: "achteraan | achterin | aan het einde van", es: "al fonde de" },
    { nl: "de lift", es: "el ascensor" },
    { nl: "de deurbel", es: "El timbre" },
    { nl: "het is fris", es: "Hace fresco" },
    { nl: "het is zonnig", es: "Hace sol" },
    { nl: "het is koud", es: "Hace frío" },
    { nl: "Het is winderig", es: "Hace viento" },
    { nl: "het is mooi weer", es: "Hace buen tiempo" },
    { nl: "het is slecht weer", es: "Hace mal tiempo" },
    { nl: "er is mist", es: "Hay niebla" },
    { nl: "er is storm", es: "Hay tormenta" },
    { nl: "er zijn wolken", es: "Hay nubes" },
    { nl: "het regent", es: "Llueve" },
    { nl: "het sneeuwt", es: "Nieva" },
    { nl: "de bliksemschicht", es: "El rayo" },
    { nl: "de donder", es: "El trueno" },
    { nl: "het licht van de bliksem", es: "El relámpago" },
    { nl: "het gazon", es: "el césped" },
    { nl: "de nachtmerrie", es: "la pesadilla" },
    { nl: "nog niet zo lang geleden", es: "hace poco tiempo" },
    { nl: "lang geleden", es: "hace mucho tiempo" },
    { nl: "de pennenzak", es: "el estuche" },
    { nl: "boetedoening", es: "penitencia" },
    { nl: "kamertemperatuur", es: "templado(a)" },
    { nl: "zacht", es: "suave" },
    { nl: "zachtjes", es: "suavemente" },
    { nl: "aangenaam", es: "agradable" },
    { nl: "onaangenaam", es: "desagradable" },
    { nl: "vochtig", es: "húmedo" },
    { nl: "droog", es: "seco(a)" },
    { nl: "rijp", es: "maduro(a)" },
    { nl: "niet rijp", es: "inmaduro(a)" },
    { nl: "geduld", es: "paciencia" },
    { nl: "tevreden", es: "satisfecho" },
    { nl: "koteletten", es: "chuletas" },
    { nl: "de boerderij", es: "la granja" },
    { nl: "de adelaar", es: "el águila" },
    { nl: "rauw (NL) | Bleu (FR) | Blue (EN)", es: "crudo(a)" },
    { nl: "saignant (FR) | rare (EN) | bloedig (NL)", es: "poco hecho" },
    { nl: "medium-rare (EN+NL) | a point (FR)", es: "al punto" },
    { nl: "half doorbakken (NL) | Medium (EN) | demi-anglais (FR)", es: "término medio" },
    { nl: "bijna doorbakken (NL) | Medium-well | Cuit (FR)", es: "tres cuartos" },
    { nl: "doorbakken (NL) | Well done (EN) | Bien cuit (FR)", es: "Muy hecho" },
    { nl: "heel veel", es: "muchísimo" },
    { nl: "héél klein", es: "pequeñisimo(a)" },
    { nl: "tegenovergestelde", es: "opuesto" },
    { nl: "héél goed", es: "buenisimo" },
    { nl: "metselaar", es: "albañil" },
    { nl: "metselwerk", es: "albañilería" },
    { nl: "timmerman | schrijnwerker", es: "carpintero" },
    { nl: "elektricien", es: "electricista" },
    { nl: "tegelzetter", es: "alicatador" },
    { nl: "vloertegels", es: "baldosas" },
    { nl: "vloertegelaar", es: "El solador" },
    { nl: "muurtegels", es: "azulejos" },
    { nl: "muurtegelaar", es: "El alicatador" },
    { nl: "het ontbijt", es: "el desayuno" },
    { nl: "het tussendoortje", es: "el almuerzo" },
    { nl: "de lunch", es: "la comida" },
    { nl: "de middagsnack", es: "la merienda" },
    { nl: "de borrelhapjes", es: "el tapeo" },
    { nl: "het avondeten", es: "la cena" },
    { nl: "verplichting", es: "obligación" },
    { nl: "advies", es: "consejo" },
    { nl: "verkleinwoord", es: "disminutivo" },
    { nl: "het verkeerslicht", es: "el semáforo" },
    { nl: "de rotonde", es: "la rotonda" },
    { nl: "succes!", es: "¡Buena suerte!" },
    { nl: "de afspraak", es: "la cita" },
    { nl: "een T-shirt met een V-hals", es: "una camiseta de pico" },
    { nl: "marineblauw", es: "azul marino" },
    { nl: "het kostuum", es: "el traje" },
    { nl: "de stropdas", es: "la corbata" },
    { nl: "de trui", es: "el jersey" },
    { nl: "een overhemd", es: "una camisa" },
    { nl: "een trainingspak", es: "un chándal" },
    { nl: "een zwempak", es: "un bañador" },
    { nl: "een jurk | een kleed", es: "un vestido" },
    { nl: "een jas", es: "un abrigo" },
    { nl: "een T-shirt", es: "una camiseta" },
    { nl: "een broek", es: "un pantalón" },
    { nl: "de pyjama", es: "el pijama" },
    { nl: "minder dan", es: "menos que" },
    { nl: "meer dan", es: "más que" },
    { nl: "slechter", es: "peor" },
    { nl: "beter", es: "mejor" },
    { nl: "veel meer", es: "mucho más" },
    { nl: "veel kleiner dan", es: "mucho más pequeño que" },
    { nl: "evenveel | x", es: "tan" },
    { nl: "interview", es: "entrevista" },
    { nl: "sollicitatiegesprek", es: "entrevista de trabajo" },
    { nl: "vacatures | jobaanbiedingen", es: "ofertas de empleo" },
    { nl: "serieus?", es: "¿En serio?" },
    { nl: "in de mode", es: "de moda" },
    { nl: "zich haasten", es: "darse prisa" },
    { nl: "de hulp | de ondersteuning", es: "la ayuda" },
    { nl: "zou u...?", es: "¿Te gustaría...?" },
    { nl: "Wat vind je ervan als...?​", es: "¿Qué te parece si...?" },
    { nl: "waarom niet...?", es: "¿Por qué no...?" },
    { nl: "het dorp", es: "el pueblo" },
    { nl: "de toiletruimte", es: "el aseo" },
    { nl: "markeerstift", es: "subrayador" },
    { nl: "tong (vis)", es: "lenguado" },
    { nl: "het ergst | waardeloos", es: "pésimo" },
    { nl: "niet opgevoed iemand", es: "grosero" },
    { nl: "taai of moeilijk te eten brood", es: "pan duro" },
    { nl: "vuil", es: "sucio" },
    { nl: "vreselijk | rampzalig", es: "fatal" },
    { nl: "het vlees ziet er heerlijk uit", es: "la carne tiene muy buen aspecto" },
    { nl: "duiven", es: "palomas" },
    { nl: "verbeelding", es: "imaginación" },
    { nl: "het landschap", es: "el paísaje" },
    { nl: "de schoonheid", es: "la belleza" },
    { nl: "blind", es: "ciego" },
    { nl: "broodkruimels", es: "migas de pan" },
    { nl: "bloempot", es: "maceta" },
    { nl: "een vijver", es: "un estanque" },
    { nl: "roodborstje", es: "petirrojo" },
    { nl: "zijn baas | zijn meester (personen of dieren)", es: "su amo" },
    { nl: "onrustig | bezorgd", es: "intranquilo(a)" },
    { nl: "de hoeken", es: "los rincones" },
    { nl: "de hoek", es: "el rincón" },
    { nl: "verbaasd", es: "sorprendido" },
    { nl: "floeren broek", es: "pantalones de pana" },
    { nl: "wol", es: "lana" },
    { nl: "vriendelijk", es: "amable" },
    { nl: "aan het einde", es: "al fondo" },
    { nl: "gestalte", es: "estatura" },
    { nl: "joviaal", es: "jovial" },
    { nl: "sigaar", es: "habano" },
    { nl: "fors | gezet | volumineus", es: "voluminoso" },
    { nl: "een kleermaker", es: "un sastre" },
    { nl: "op maat", es: "a la medida" },
    { nl: "mosselen", es: "mejillones" }
];
